version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "80:4000"
    environment:
      - PORT=4000
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
