version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
